### PR TITLE
Fix 408 Request Timeout errors with wake_up api call

### PR DESCRIPTION
**Pull request by ejsuncy**
The HTTP spec says for code 408 that 

> the client MAY repeat that request on a new connection.

So polling seems like the correct solution.

### CODE REVIEW

**Comment by ejsuncy** [comment]
Working out kinks after further testing

**Comment by ejsuncy** [comment]
Ok, kinks worked out. Should be good to go.

**Comment by gglockner** [comment]
Can you test the 2.0 release? This was completely rewritten using Python requests; I'm not sure whether the 408 errors you reported are the result of the old implementation or the result of Tesla's APIs. If you see it again, then I'd like to investigate a new fix from the 2.0 release.

**Comment by gglockner** [comment]
I'm closing this due to no response, but feel free to open an issue if you see this in the 2.0 release.

**Pull request closed without merging**
