### PR TITLE
Allow passing of parameters/data to command

### PR DESCRIPTION
**Pull request by the-mace**
Thanks!

### CODE REVIEW

**Comment by gglockner** [comment]
Great change, will pull it now.

**Comment by the-mace** [comment]
Thanks, by the way I tested it with sunroof controls:

`
def trigger_sunroof(c, car, state):
    logT.debug("Setting sunroof to %s for %s", state, car)
    for v in c.vehicles:
        if v["display_name"] == car:
            cmd = {"state": state}
            res = v.command("sun_roof_control", data=cmd)
            logT.debug("Garage door trigger: %s", res)
    return
`
ugh, don't know about pasting snips

**Comment by gglockner** [comment]
The change made sense, and your code was clean.  Appreciated!

**Comment by the-mace** [comment]
No problem. I mentioned the library in a post here:
http://www.teslarati.com/tesla-api-controlling-model-s-model-x/

Thanks again.

**Pull request merged**
